server:
  port: 8331

spring:
  application:
    name: consumer-service
  # 配置 rabbitmq
  rabbitmq:
    host: 192.168.200.6
    port: 5672
    username: admin
    password: admin

    # 开启手动确认
    # 当收到消息时 消费端处理完成后 再返回 ack
    listener:
      simple:
        acknowledge-mode: manual
